### ISSUE TITLE
Critical issue on resolving empty `href`s

### ISSUE THREAD

**Issue by tommedema** [jrit/web-resource-inliner#34]
Currently, links with empty hrefs are being parsed as if they contain `/` or `./`:

If a page has this:

```
<link href="" rel="stylesheet" />
```

It will end up downloading the root domain of the site, and then putting the HTML of the site in the style tags of that site.

This is a bug in the way you resolve paths. An empty href is a non-existant path, and should not resolve to anything.

_under http mocking describe_
```
        it( "should not try to inline empty links", function( done )
        {
            const content = '<link href="" rel="stylesheet" />'

            inline.html( {
                    fileContent: content,
                    strict: false,
                    relativeTo: baseUrl
                },
                function( err, result )
                {
                    testEquality( err, result, expected, done );
                }
            );
        } );
```

It's trying to request the root path (`baseUrl`):

```
  0 passing (42ms)
  1 failing

  1) html (http mocking) should not try to inline empty links:
     Uncaught Error: EISDIR: illegal operation on a directory, read
      at Object.fs.readSync (fs.js:693:18)
      at tryReadSync (fs.js:557:20)
      at Object.fs.readFileSync (fs.js:600:19)
      at FauxJax.<anonymous> (test/spec.js:500:34)
      at IncomingMessage.<anonymous> (node_modules/faux-jax/index.js:108:8)
      at endReadableNT (_stream_readable.js:1054:12)
      at _combinedTickCallback (internal/process/next_tick.js:138:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

I will try to make a PR for this ASAP since this is affecting a critical part of my app.

**Comment by tommedema** [comment]
@jrit Fixed in #35. Would appreciate merge and publish to npm with minor or patch version.
